apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ucebnice.fullname" . }}-secret
  labels:
    {{- include "ucebnice.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  {{- $pgHost := printf "%s-postgres.%s.svc.cluster.local" (include "ucebnice.fullname" .) .Release.Namespace }}
  {{- $pgUser := .Values.postgresql.auth.username }}
  {{- $pgPass := .Values.postgresql.auth.password }}
  {{- $pgDb := .Values.postgresql.auth.database }}
  DATABASE_URL: "postgresql://{{ $pgUser }}:{{ $pgPass }}@{{ $pgHost }}:5432/{{ $pgDb }}?sslmode=disable"
  {{- end }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}