apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: ucebnice-production
spec:
  encryptedData:
    .dockerconfigjson: AgDKg9ZipypTVSJcY5b4ipiSwpA2NxQPF0L/9qCiE2gBApWea7FnEcRsHpkmfwWlqHLcy8czgjgYjv0mbBbkS3CbhTn1U5wQar9FKcj5qwePtck4/6rRsTy6n6VRWovyVzf5+8+ZAsXqTg8k8NXSzbpzb+ZT46qasZZPN7b/Y7urwHxkOa+bH5tb6GR9LYuGs6rUPEOEe8zdAeZrDhFGTRD3b7l1cbghNOWTLzdfCuJyAub9uC+vQMRhedbPwDyNZaPGL/F6u+ZLqnuSCo8pR6IjeA5Egdrq/S1Xht8gRYHwkvky8YKWMDo9CjkftYdaGb0WLxSdho66/tDMDKWnjTEokH7iHcPcRMmq//k+AdpZOKzE220tZUNY/jTDCajxqigcb/Fvw3+AS42bSSH8l75eK8JlpAh5n2kUH7PAEXBpvbAzPmKP0A2j7snQiWLEBKM5Q3CRTY9wt2cdJA97vlAXddSQrcmP54lXmdFier0ob+r2CQLyfU28htbIBYbV9kuMoB92BkXhV/FZ0icqAMtgpveGV3O9Tsw6L+taBKsV/hDBnVnj4+dR9kuHnvWvjN+gO8UphddgJjIXw+fZ/ETTCc8qwHxevvzuYSdAJvxHWzmU9Ff/1D5XF/jaf9571gWm5Ko445QA0VcsHow3ywhfbkPBmKmbP8rUugGYJKH2hj+7auulc7dvDGu3YuoQcXhfT4bopExR+/kJUDGJ6ls47V9Jwg5GyEibQfoqigZ8OqsMTXKXaoOu2x4m7TVGtAgKup4KwO/qITRr0KTPGWRH8FIL0fxk8Kuj8dPqDe1rckJ9a6CsRAn+GieddSXdctbezxEtFeDbUmI4ZktmEgLblOK27orxgpuWVXtpzgvg/3eXMoJESStBt+o3rQWiVRmhjpOJAGIrB3ngkvDuT9+kxR/whhznK3CvzGKyi+Reen0H6s/qS9B8V9kgX/UqWPPb7EDrJ9gINnEgkMV+3nji7WJ61XO8PZxgZGs9xhZxVRBAsA==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: ucebnice-production
    type: kubernetes.io/dockerconfigjson
---
