apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: ucebnice
spec:
  encryptedData:
    .dockerconfigjson: AgCSypJIreBv7bH7WMmv+B4PUHC+kKos8mBgAr+6ylLYTWwh4pjquOwB16pJOZPSrFQFodIwl7yg94yt86P06DVvGY27sXb7glLUVVaz+Ur5IPdfzSs0m1U/1ctQuDBxZPwkdFIpkzK+G+MRzfrqgihBw6bL49kV2MJEYEzqXB794zUFl5X66/UXSoZow5Dd5GgKjmk+ObTK+V4RWIZ6SuB90iov2vlsCPdq04q1dDP/SHWOesauyqDeyxMv8HeS8FAvN+4WJNEaNuNU3F5dzHIgENl6KPRMLqH04LMWPLOBdW0hyuThD9VWn70RT44jrRxZeQFf9cAaQAYLh4hXt86L7nt8AIOqw4nLkFW8SS9o3jp+QQLs33x3lkYfjl5dM3T8nrwPNN4McISTePFShkqgR1FJ2N+SRepPNHtfrutZxf0MuAtOqzZNhAS6KWLT2uODPS/SspjG9bU1IfW1wOlZyVIVMS1gwa4hK5XkbdTVwqDyJvZfETiXBwsKtjxcFUToGpF7DmqXeJ0F35ByI+Zm6lvH5FdFDs0PZlsvizlbEJe61+6ylq/tvwD91Cje9LQyxTFjLH64vcC9IIpVq5taT/og87BIde/YvwBNm6+9h892fXxh6/FBHexHTPtA/2iXPsaBXYx02mIfoXTW0rAl51rm/gzAR5SesyhPoG/i6QBC2k1FAJ1sDAdwZp81YvE/J+ZF4VWtXzQssoqWXZh3SyA+TI4eIM61+SGm86EXlGpbW0oON/RtpGq1a4Tj+2Fq9EPX3kciP4i68rIn2sD2XHaeiNM7ioVMYztq8WFS+P7/s5uldZEmNTXY7lXpG5xc2sZ9yfXmDJGCdGeNKO8O5meO9DsFKKj+SIUNBajW4RPOhJZR4RqPBKjLAQ7a+S5CuA21KdLEsgd/7v0kHIGGoqKrw6SqvcqBXeHjaOndvDDMTvHxg858itYWQqaErmifF951PIdZeictzSWJzfVh2mWivP+gYaWLqD12YuSgz7PkMg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: ucebnice
    type: kubernetes.io/dockerconfigjson
---
