apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: ucebnice-production
spec:
  encryptedData:
    .dockerconfigjson: AgACacj/mYte4Dw7UbciHlepmGX//e1uD89spxuIRhSsfG61G/JwpCU9pQnTCBp2GLYpnF3QbCwnRZe8OSO68yBHoSgKES9AfuTJcLSas3vGIcilec92NkVLTOx+EKSeps3X8O1dStrR5yBv5CvFCc+36lDOm902hYTzJqmbZfR2dfTmAIsPw0d+on2wtuvvUEiudnXGVveWTSu0bjPv912sMd8TLnUpjLGkf2C47mn943HH2CodGi0DpKzIufKLqSdZUG/e6kezzpElGvODXJsbZ66GKtoMGt+DhEOB15+GfVAZL19fY0s6gpPQlNXjJqo9dZHNp1eczYA2E2lh6+mtmPcQ3UAOUEt56BIC+/gLUHZn+Gcl8j6NzOGBqlXMbgoBrABb2BOfQ01mithYsu9mrAvc2+g5Qvt8mS0xj3u0lXjMoJ8Yf0zQh9D5ImoxEM4Gpw6kDKRfdKwYQXQUV5FmTvEKiTv3HlqkAcxYztYaHCEEmkXnplT+Yo4uJJf0unj9Cy1xIhgl0yGG4Pwh4bb2yINN5QMjQaiY4CXmN8oa0fMdRyyS3aTVfo9GepJq2n8vw62/j7cWD7xDewA2iZDWm9UsP3v92bmRq03cNovVOL8Lv/nkMTeEZHW+7mgcI//B6IlFJD4ZHLS+7I3laYfSOwFyBlcIWEIWbOm2Vd6Pd0zzHR7uPvUSJjujHxisbMprOUQOzB0x98xu8aPP7lo22/dLSC+rKtaTiMsXQ/TQzOkgGGzeG1EtKuw2h0fjd5NRQeIxC8iVYGRhfMjhkGysIabTkXEZ9m99dgc+epnGubZ4OWvvzusmvz/Ojb+oDRSNo/I38h8M624w/Zr/IxsSQa8aqN0qQqSiW6jI4VB6nTmlsabP0BJ7YwEjdVjF6EeYjFudJsabIxes8JUiVXH7llW+NYlftnn473L7jX5AXtzc++DOdzah+mUQHhqShcpO9ckiZuAOjOChENVhLutlcjOmWXF6b1NHtEDNUSQgjSPoMQ==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: ucebnice-production
    type: kubernetes.io/dockerconfigjson
---
