apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ucebnice-postgres-secret
  namespace: ucebnice-production
spec:
  encryptedData:
    password: AgBnz+fUMUZQCw2fYCX4k9AbkGkPXeQ495G9b4OXqhENBaoosKe44xpCesuAKtUIJJt5SoRG+IXgLosGKiBNRe5mn3xgjndyTtkEv+1jy2/3p/QeFuij359UWeiglhQ1tQPtzenOpnkD1+YoijFqAdVXBK4qW22eOxcNxIgnqnNKJQGzrGZbjJaAURQct/GMs7sjoItGfekoLsXxh3h9wqoMAN9q5D4LRPZyhO/4/XJYSFy3XG1nBjhU4oOUYrN/rqZO3Va+N2LdzTciksH0gVEh0RuvjvLmmX/XoaHBzCwIVoyzPItwht9kEvFLxztI9cqPD8TBGQ3xN90Q+QrQUo6lbBNopYzz0wtYko2J+SjrdGBRnEWDgES+k55rZSQBZqs74wdEHV5jO2mnB57pZyeu6JA2PvAY4LWZjCOzfuFp5awwldi/4gz73hi9+N1jApCzzbHvGPsigwgSr9HU3HnJoAWN8CzT9o5wWjo4GaBQYcSbruMIVmsfYipuQ8zZZPn4PRNXLEZARNj6Z/LMTC197AGg7snMgheKMCL4sFCh7gFg6/rdu6yopbkkg0WvXCI0mem6HFAqr77pR8GTD9yyNfiO7yz0a8HBYZw4R3wMv3tr3FuLEz6T+ES2AcdYBN4nHAnnP5U06RQPxzDS4TPbqimWgLyQ+GPTczcTDtX2/LhiHVwMOhqn+KAFrHyFkYBhDr6A7QjujEoH1KX0NH2nLO0T5oKHX7k4hbvTksa2qEsNEW3XG784deS8WA==
    username: AgCLw81sjRoiiHCMGb7O9tS9kt8gU7OeAyIJlUMgMB60bPkhEQpwCjVl7IUOJ3+jWu3OfoGLGy5jwxmmNN/pyc+pa5IK8aOLtcYHwAOWuK4oobJrg/J1Zio9P86+kzAErg0x+ah9sL40PUpyyWuQSv1RHHLd6TI/mDlxaTlRP3+cLMUAkPvdcWpjTRlRPqdq4vPlfuMV1Jgv3Ul9VAE2a8bGDhKmLXcc1dRRnC40fQka2X+2aBsR5451RQJji2JJSoFaTTjve+YAsjj48r90RXdSbi6cyadzOHO02YNckYcdHVbwZCiPV2xLQwO4ygBcBgzQqC2Xthv9bhy5wQzTYIzSr3/001z5RaBGzGLtfK8/E9IifJQFoBI5DX0Qfto/x4twdZ5/cyGkfTlOC7lxOpP2s675C705Z1xjURFhl9OocP7OKT6vmFdZSiTAMDQtZJTOcQNM0eREkM71VVBQ0JtLPJRhM1eqs06ZpQCyWTtzrt/fLF0vUZmDgDk70GG19R3ggNrsuPN+ZkMWpKpVpEQ+yAujd0UO/AOg25ZrKKwQyWHZmRIAxk0SE+to+S05LtjWLTvktETz3oz/yS/M17iKkY3fTg92OSI5MX00eSFcZBhWEHIhYUIQySgY04MovAIQ2UMd80y+Bh/GX0bgTeySz82JDK12dvNTyvOEtIQSaOXxNhYyVTDiPv8UBS3i/txm9o7cLv+Leg==
  template:
    metadata:
      creationTimestamp: null
      name: ucebnice-postgres-secret
      namespace: ucebnice-production
---
