#!/bin/sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

export PATH="$HOME/.npm-global/bin:/usr/local/bin:$PATH"
export PATH="./node_modules/.bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

npm run type-check
npm run lint
npm test -- --runInBand
